import org.apache.commons.configuration2.builder.BuilderConfigurationWrapperFactory.BuilderConfigurationWrapperInvocationHandler;
public class FunctionUse2298 {
public void funcUse() {
BuilderConfigurationWrapperInvocationHandler builderconfigurationwrapperinvocationhandler = new BuilderConfigurationWrapperInvocationHandler();
builderconfigurationwrapperinvocationhandler.invoke(null,null,null);
}
}